downstream_dependencies:
  - datanator
  - obj_tables_test_migration_repo
  - wc_kb
  - wc_lang
  - wc_rules
  - wc_sim
email_notifications:
  - jonrkarr@gmail.com
  - arthur.p.goldberg@mssm.edu
static_analyses:
  ignore_unused_requirements: []
  ignore_missing_requirements:
    - configobj
